
SRC = ..\source

CC = cl

CFLAGS = /O2 /Oi /GL /Gy /GT /D _WIN32 /D UNIT_TEST /D INTEGRATION_TEST /I$(SRC) /I..\pcre

LDFLAGS =

# CFLAGS += /MTd /D _DEBUG /D DEBUG /DEBUG /Zi

LIBS = kernel32.lib user32.lib ws2_32.lib crypt32.lib advapi32.lib shlwapi.lib

cache: shared.obj share.obj agent_cache.obj alloc.obj
	$(CC) $(CFLAGS) -o cache test_cache.c agent_cache.obj shared.obj share.obj alloc.obj rwlock.obj $(LDFLAGS) $(LIBS)

alloc: alloc.obj shared.obj share.obj
	$(CC) $(CFLAGS) -o alloc test_alloc.c shared.obj share.obj alloc.obj $(LDFLAGS) $(LIBS)

rwlock: rwlock.obj
	$(CC) $(CFLAGS) -o rwlock test_rwlock.c rwlock.obj $(LDFLAGS) $(LIBS)

agent_cache.obj: $(SRC)\agent_cache.h $(SRC)\agent_cache.c alloc.obj rwlock.obj
	$(CC) /c $(CFLAGS) $(SRC)\agent_cache.c

alloc.obj: $(SRC)\alloc.h $(SRC)\alloc.c 
	$(CC) /c $(CFLAGS) $(SRC)\alloc.c

rwlock.obj: $(SRC)\rwlock.h $(SRC)/rwlock.c
	$(CC) /c $(CFLAGS) $(SRC)\rwlock.c

shared.obj: $(SRC)\shared.c
	$(CC) /c $(CFLAGS) $(SRC)\shared.c

share.obj: $(SRC)\share.h $(SRC)\share.c
	$(CC) /c $(CFLAGS) $(SRC)\share.c

all: cache alloc rwlock

clean:
	-del *.obj *.exe

